## Libraries

In [ ]:
pip install pyvi

     |████████████████████████████████| 8.5 MB 6.9 MB/s 
     |████████████████████████████████| 743 kB 69.6 MB/s 


In [ ]:
import pandas as pd
import numpy as np

from pyvi import ViTokenizer, ViPosTagger
import string
import pickle
from sklearn.metrics import f1_score, accuracy_score


# Model-based Data:

### number of track_name and artists:

In [ ]:
user1_csv = pd.read_csv('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/user1/user1.csv')
user2_csv = pd.read_csv('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/user2/user2.csv')
user3_csv = pd.read_csv('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/user3/user3.csv')

In [ ]:
print('number of artists that user1 listened to:  ', len(user1_csv['artists'].unique()))
print('number of songs that user1 listened to:  ', len(user1_csv['track_name'].unique()))

number of artists that user1 listened to:   40
number of songs that user1 listened to:   69


In [ ]:
print('number of artists that user2 listened to:  ', len(user2_csv['artists'].unique()))
print('number of songs that user2 listened to:  ', len(user2_csv['track_name'].unique()))

number of artists that user2 listened to:   91
number of songs that user2 listened to:   126


In [ ]:
print('number of artists that user3 listened to:  ', len(user3_csv['artists'].unique()))
print('number of songs that user3 listened to:  ', len(user3_csv['track_name'].unique()))

number of artists that user3 listened to:   73
number of songs that user3 listened to:   90


In [ ]:
user1_train_csv = pd.read_csv('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/user1/user1_train.csv')
user2_train_csv = pd.read_csv('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/user2/user2_train.csv')
user3_train_csv = pd.read_csv('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/user3/user3_train.csv')

In [ ]:
user1_train_csv

artists  ... label
0                          Bằng Kiều  ...     0
1                            D1Verse  ...     0
2                           Lâm Hùng  ...     0
3                               ERIK  ...     0
4                      Sơn Tùng M-TP  ...     1
5                         Lam Truong  ...     0
6                       Phương Thanh  ...     0
7                           Đức Phúc  ...     0
8                      Sơn Tùng M-TP  ...     1
9                      Sơn Tùng M-TP  ...     1
10                      Jimmi Nguyen  ...     0
11                     Sơn Tùng M-TP  ...     1
12                        Việt Quang  ...     0
13      Đen and Kimmese and Lynk Lee  ...     0
14                    Tạ Quang Thắng  ...     0
15                         Nhu Quynh  ...     0
16                       Bich Phuong  ...     0
17  MIN and JustaTee and Yuno Bigboi  ...     0
18    Noo Phước Thịnh and Tonny Viet  ...     0
19                     Sơn Tùng M-TP  ...     1
20                     Sơn Tùng M-TP  ...     1
21                     Sơn Tùng M-TP  ...     1
22                            JayKii  ...     0
23                          Thu Minh  ...     0
24                     Sơn Tùng M-TP  ...     1
25         Lam Truong and Minh Tuyết  ...     0
26                         Bằng Kiều  ...     0
27                   Vũ. and Kimmese  ...     0
28                     Sơn Tùng M-TP  ...     1
29                     Sơn Tùng M-TP  ...     1
30                               Đen  ...     0
31                      Nguyễn Thắng  ...     0
32                     Sơn Tùng M-TP  ...     1
33                          Đông Nhi  ...     0
34             Đan Trường and Cẩm Ly  ...     0
35                     Sơn Tùng M-TP  ...     1
36                         Tuấn Hưng  ...     0
37                     Sơn Tùng M-TP  ...     1
38                         Tuấn Hưng  ...     0
39                        Lam Truong  ...     0
40                            T Team  ...     0
41                     Sơn Tùng M-TP  ...     1
42                     Sơn Tùng M-TP  ...     1
43                          Tú Quyên  ...     0
44                        Trung Quân  ...     0
45                               TIA  ...     0
46        Dick and Ngắn and CHARLES.  ...     0
47                            Cẩm Ly  ...     0
48                     Sơn Tùng M-TP  ...     1
49                         Tuấn Hưng  ...     0
50                     Sơn Tùng M-TP  ...     1
51           Lam Truong and Đông Nhi  ...     0
52                            Tra My  ...     0
53                     Will and Rtee  ...     0
54                     Sơn Tùng M-TP  ...     1
55             Đan Trường and Cẩm Ly  ...     0
56                    Phan Dinh Tung  ...     0
57                        Lam Truong  ...     0
58                         Hien Thuc  ...     0

[59 rows x 21 columns]

### labels:

In [ ]:
user1_train_csv['mode'].value_counts()

1    32
0    27
Name: mode, dtype: int64

In [ ]:
user1_train_csv['time_signature'].value_counts()

4    57
3     2
Name: time_signature, dtype: int64

In [ ]:
user1_train_csv.columns

Index(['artists', 'track_name', 'id', 'uri', 'track_href', 'analysis_url',
       'popularity', 'danceability', 'energy', 'key', 'loudness', 'mode',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature', 'label'],
      dtype='object')

In [ ]:
user1_train_csv['label'].value_counts()

0    41
1    18
Name: label, dtype: int64

In [ ]:
user2_train_csv['label'].value_counts()

0    79
1    37
Name: label, dtype: int64

In [ ]:
user3_train_csv['label'].value_counts()

0    55
1    25
Name: label, dtype: int64

In [ ]:
# list of artists and track_name for all 3 users:
text_feature1 = user1_train_csv['artists'].tolist() + user1_train_csv['track_name'].tolist()
text_feature2 = user2_train_csv['artists'].tolist() + user2_train_csv['track_name'].tolist()
text_feature3 = user3_train_csv['artists'].tolist() + user3_train_csv['track_name'].tolist()

text_feature = text_feature1 + text_feature2 + text_feature3 + ['unk'] # for unknown words

In [ ]:
text_feature 

['Bằng Kiều',
 'D1Verse',
 'Lâm Hùng',
 'ERIK',
 'Sơn Tùng M-TP',
 'Lam Truong',
 'Phương Thanh',
 'Đức Phúc',
 'Sơn Tùng M-TP',
 'Sơn Tùng M-TP',
 'Jimmi Nguyen',
 'Sơn Tùng M-TP',
 'Việt Quang',
 'Đen and Kimmese and Lynk Lee',
 'Tạ Quang Thắng',
 'Nhu Quynh',
 'Bich Phuong',
 'MIN and JustaTee and Yuno Bigboi',
 'Noo Phước Thịnh and Tonny Viet',
 'Sơn Tùng M-TP',
 'Sơn Tùng M-TP',
 'Sơn Tùng M-TP',
 'JayKii',
 'Thu Minh',
 'Sơn Tùng M-TP',
 'Lam Truong and Minh Tuyết',
 'Bằng Kiều',
 'Vũ. and Kimmese',
 'Sơn Tùng M-TP',
 'Sơn Tùng M-TP',
 'Đen',
 'Nguyễn Thắng',
 'Sơn Tùng M-TP',
 'Đông Nhi',
 'Đan Trường and Cẩm Ly',
 'Sơn Tùng M-TP',
 'Tuấn Hưng',
 'Sơn Tùng M-TP',
 'Tuấn Hưng',
 'Lam Truong',
 'T Team',
 'Sơn Tùng M-TP',
 'Sơn Tùng M-TP',
 'Tú Quyên',
 'Trung Quân',
 'TIA',
 'Dick and Ngắn and CHARLES.',
 'Cẩm Ly',
 'Sơn Tùng M-TP',
 'Tuấn Hưng',
 'Sơn Tùng M-TP',
 'Lam Truong and Đông Nhi',
 'Tra My',
 'Will and Rtee',
 'Sơn Tùng M-TP',
 'Đan Trường and Cẩm Ly',
 'Phan Dinh Tung

In [ ]:
from pyvi import ViTokenizer, ViPosTagger
import string
# Define the function to remove the punctuation
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text

def handle_text(text):
  #remove punctuation:
  temp = remove_punctuations(text)

  #word tokenize:
  temp = ViTokenizer.tokenize(temp)

  #lowercase:
  temp = temp.lower()

  return temp

tokenized_text_feature = []
for sentence in text_feature:
  tokenized_text_feature.append(handle_text(sentence))

In [ ]:
tokenized_text_feature

['bằng_kiều',
 'd1verse',
 'lâm_hùng',
 'erik',
 'sơn_tùng mtp',
 'lam_truong',
 'phương_thanh',
 'đức_phúc',
 'sơn_tùng mtp',
 'sơn_tùng mtp',
 'jimmi_nguyen',
 'sơn_tùng mtp',
 'việt_quang',
 'đen and kimmese and lynk_lee',
 'tạ_quang_thắng',
 'nhu_quynh',
 'bich_phuong',
 'min and justatee and yuno_bigboi',
 'noo phước_thịnh and tonny_viet',
 'sơn_tùng mtp',
 'sơn_tùng mtp',
 'sơn_tùng mtp',
 'jaykii',
 'thu_minh',
 'sơn_tùng mtp',
 'lam truong and minh_tuyết',
 'bằng_kiều',
 'vũ and kimmese',
 'sơn_tùng mtp',
 'sơn_tùng mtp',
 'đen',
 'nguyễn_thắng',
 'sơn_tùng mtp',
 'đông_nhi',
 'đan_trường and cẩm_ly',
 'sơn_tùng mtp',
 'tuấn_hưng',
 'sơn_tùng mtp',
 'tuấn_hưng',
 'lam_truong',
 't_team',
 'sơn_tùng mtp',
 'sơn_tùng mtp',
 'tú_quyên',
 'trung_quân',
 'tia',
 'dick and ngắn and charles',
 'cẩm_ly',
 'sơn_tùng mtp',
 'tuấn_hưng',
 'sơn_tùng mtp',
 'lam truong and đông_nhi',
 'tra_my',
 'will and rtee',
 'sơn_tùng mtp',
 'đan_trường and cẩm_ly',
 'phan_dinh_tung',
 'lam_truong',
 '

## prepare trainable data:

1. embed artists and track_name -> transform to 1d array
2. create a vector of features:  

'popularity', 'danceability', 'energy', 'key', 'loudness', 'mode',
'speechiness', 'acousticness', 'instrumentalness', 'liveness',
'valence', 'tempo', 'duration_ms'
3. concatenate 1 and 2 -> X_, 
y is label

references
* https://phamdinhkhanh.github.io/2019/04/29/ModelWord2Vec.html

In [ ]:
from gensim.models import Word2Vec

sentences = [[item for item in doc.split()] for doc in tokenized_text_feature]
model = Word2Vec(sentences, min_count = 1, size = 150, window = 10, sg = 1, workers = 8)
model.train(sentences, total_examples = model.corpus_count, epochs = 10)

(11027, 14320)

In [ ]:
import pickle

pickle.dump(model, open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/Models/saved_models/w2v.pickle', 'wb'))

In [ ]:
# Lấy véc tơ biểu diễn của từ bằng_kiều
print('embedding vector shape: ', model.wv['bằng_kiều'].shape)
model.wv['bằng_kiều']


embedding vector shape:  (150,)


array([ 1.56763257e-04, -2.63365451e-03,  4.46679536e-04, -2.13428983e-04,
        1.95131556e-03,  1.19418430e-03,  1.79230631e-03,  3.00016743e-03,
        4.26732935e-04, -3.51233059e-03, -3.30833299e-03, -1.53313135e-03,
        1.20026853e-04, -3.49426433e-03,  1.31362141e-03, -1.42958469e-03,
        1.95116887e-03, -2.75707734e-03,  1.85685046e-03, -3.28689138e-03,
        2.50174175e-03,  2.16563186e-03, -2.87912809e-03,  8.67920287e-04,
       -6.51503738e-04,  2.35493248e-03,  6.13097218e-04, -1.88603811e-03,
        4.62603959e-04,  8.92618613e-04,  3.11108958e-03, -2.73099565e-03,
       -7.06126957e-05,  3.01263994e-03, -1.28126339e-04,  1.14782748e-03,
       -2.36164592e-03, -1.05118888e-04, -4.45752084e-05,  1.37013779e-03,
        1.21395069e-03, -8.53507547e-04,  6.49696798e-04,  1.81924156e-03,
        2.08295975e-03, -2.61081223e-05,  2.17026845e-03, -1.16548174e-04,
        2.12661433e-03, -1.99792790e-03,  2.61137378e-03,  1.82393123e-03,
        1.42935710e-03,  

In [ ]:
# Lấy các từ có mối liên hệ gần nhất với 1 từ dựa trên khoảng cách
model.most_similar('bằng_kiều')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  


[('sương_khói', 0.2956705093383789),
 ('thuy_kieu', 0.27859485149383545),
 ('mai_đây', 0.2760903239250183),
 ('yếu_đuối', 0.2756480574607849),
 ('de', 0.264539510011673),
 ('rồi', 0.25644299387931824),
 ('nao_original', 0.2533719837665558),
 ('mà', 0.25332775712013245),
 ('nhà', 0.23817305266857147),
 ('tu', 0.23806016147136688)]

In [ ]:
import numpy as np

def get_artist_trackname_vector(user1_csv):

  user1_artist_trackname = []

  for i in range(len(user1_csv)):
    artist_vector = model.wv[[item for item in handle_text(user1_csv['artists'][i]).split()]]
    artist_vector = np.mean(artist_vector, axis=0)

    track_name_vector = model.wv[[item for item in handle_text(user1_csv['track_name'][i]).split()]]
    track_name_vector = np.mean(track_name_vector, axis=0)

    general = np.concatenate((artist_vector, track_name_vector), axis=0)
    user1_artist_trackname.append(general)
  return user1_artist_trackname

user1_train_artist_trackname = get_artist_trackname_vector(user1_train_csv)
user2_train_artist_trackname = get_artist_trackname_vector(user2_train_csv)
user3_train_artist_trackname = get_artist_trackname_vector(user3_train_csv)

In [ ]:
# 2
features = ['popularity', 'danceability', 'energy', 'key', 'loudness', 'mode',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms']

In [ ]:
def get_DIGITAL_FEATURE(user1_csv):
  DIGITAL_FEATURE = []
  for i in range(len(user1_csv)):
    digital_feature = []
    for feature in features:
      digital_feature.append(user1_csv[feature][i])
    DIGITAL_FEATURE.append(digital_feature)

  return DIGITAL_FEATURE

user1_train_DIGITAL_FEATURE = get_DIGITAL_FEATURE(user1_train_csv)
user2_train_DIGITAL_FEATURE = get_DIGITAL_FEATURE(user2_train_csv)
user3_train_DIGITAL_FEATURE = get_DIGITAL_FEATURE(user3_train_csv)

In [ ]:
df_user1_train = pd.DataFrame()
df_user1_train['artist_trackname'] = user1_train_artist_trackname
df_user1_train['DIGITAL_FEATURE'] = user1_train_DIGITAL_FEATURE

df_user2_train = pd.DataFrame()
df_user2_train['artist_trackname'] = user2_train_artist_trackname
df_user2_train['DIGITAL_FEATURE'] = user2_train_DIGITAL_FEATURE

df_user3_train = pd.DataFrame()
df_user3_train['artist_trackname'] = user3_train_artist_trackname
df_user3_train['DIGITAL_FEATURE'] = user3_train_DIGITAL_FEATURE

In [ ]:
def get_general_feature(df_user1):
  general_feature = []
  for i in range(len(df_user1)):
    temp = np.concatenate((df_user1['artist_trackname'][i], df_user1['DIGITAL_FEATURE'][i]), axis=0)
    general_feature.append(temp)

  return general_feature

user1_train_general_feature =  get_general_feature(df_user1_train)
user2_train_general_feature =  get_general_feature(df_user2_train)
user3_train_general_feature =  get_general_feature(df_user3_train)

In [ ]:
def get_X(user1_general_feature):
  X = []
  for general_feature in user1_general_feature:  
    temp = general_feature.tolist()
    X.append(temp)

  return pd.DataFrame(X)

user1_X_train = get_X(user1_train_general_feature)
user2_X_train = get_X(user2_train_general_feature)
user3_X_train = get_X(user3_train_general_feature)


In [ ]:
user1_X_train

0         1         2         3    ...     309    310      311       312
0   0.000157 -0.002634  0.000447 -0.000213  ...  0.1230  0.262   78.073  282307.0
1   0.000203  0.001437 -0.001533  0.001167  ...  0.1860  0.620  126.029  190200.0
2   0.002220  0.003156 -0.001761  0.000428  ...  0.0543  0.475  131.982  257533.0
3  -0.002033  0.003950 -0.000464  0.002697  ...  0.1200  0.329  170.063  291529.0
4   0.001177  0.002950 -0.000194 -0.000059  ...  0.0784  0.752  109.990  222981.0
5   0.001938 -0.001420  0.000157 -0.001082  ...  0.2400  0.483  160.020  270240.0
6  -0.002192 -0.001774 -0.002482 -0.001479  ...  0.0894  0.214  111.720  213682.0
7   0.002166 -0.001706  0.003331 -0.001562  ...  0.3070  0.191   67.043  246312.0
8   0.001177  0.002950 -0.000194 -0.000059  ...  0.1160  0.186  146.143  247655.0
9   0.001177  0.002950 -0.000194 -0.000059  ...  0.2440  0.429   78.246  216000.0
10  0.002782 -0.001956 -0.000186 -0.002962  ...  0.0773  0.204  107.040  278805.0
11  0.001177  0.002950 -0.000194 -0.000059  ...  0.1110  0.531  127.073  275906.0
12  0.003243  0.002037  0.000619 -0.001988  ...  0.0586  0.722  120.041  228833.0
13  0.002334  0.001830 -0.001944  0.003650  ...  0.1470  0.613  143.863  547154.0
14  0.002267  0.001942  0.001387 -0.001080  ...  0.1080  0.310   86.001  216279.0
15 -0.001050 -0.002678  0.001546  0.001849  ...  0.0890  0.186   71.196  285960.0
16 -0.000394 -0.003234  0.002800  0.002502  ...  0.3400  0.291  111.917  279439.0
17  0.001202  0.002891 -0.001771  0.005071  ...  0.0756  0.803  114.986  218087.0
18  0.001216  0.002417 -0.000761  0.003066  ...  0.1830  0.437   88.595  256261.0
19  0.001177  0.002950 -0.000194 -0.000059  ...  0.0874  0.476  120.022  188082.0
20  0.001177  0.002950 -0.000194 -0.000059  ...  0.1530  0.487  102.992  233010.0
21  0.001177  0.002950 -0.000194 -0.000059  ...  0.1280  0.107  140.083  293112.0
22  0.000836  0.000533 -0.000166 -0.002903  ...  0.1050  0.305  153.878  308703.0
23  0.002394 -0.001377 -0.001364  0.002980  ...  0.1280  0.247  138.013  301009.0
24  0.001177  0.002950 -0.000194 -0.000059  ...  0.1550  0.157  130.050  318093.0
25  0.003082  0.001741 -0.000668  0.002672  ...  0.0991  0.350  204.691  288707.0
26  0.000157 -0.002634  0.000447 -0.000213  ...  0.1190  0.254   78.058  282320.0
27  0.002341  0.001299 -0.003124  0.003921  ...  0.2940  0.448  132.968  227487.0
28  0.001177  0.002950 -0.000194 -0.000059  ...  0.0753  0.389  125.031  134400.0
29  0.001177  0.002950 -0.000194 -0.000059  ...  0.1060  0.722  131.011  218628.0
30  0.001835  0.001003  0.000979 -0.000671  ...  0.1090  0.480   91.012  217256.0
31 -0.002346 -0.000247 -0.000363 -0.000847  ...  0.3620  0.178   92.061  329267.0
32  0.001177  0.002950 -0.000194 -0.000059  ...  0.2020  0.497  155.907  301538.0
33 -0.000450 -0.000327  0.003016 -0.001608  ...  0.0817  0.332  173.946  208973.0
34  0.002264  0.002298  0.000423  0.002720  ...  0.1620  0.413  139.818  249443.0
35  0.001177  0.002950 -0.000194 -0.000059  ...  0.1330  0.166  135.062  232889.0
36  0.002086  0.000509 -0.000234 -0.000225  ...  0.0696  0.866  127.868  258064.0
37  0.001177  0.002950 -0.000194 -0.000059  ...  0.1010  0.312   95.582  279838.0
38  0.002086  0.000509 -0.000234 -0.000225  ...  0.1210  0.240  149.538  349539.0
39  0.001938 -0.001420  0.000157 -0.001082  ...  0.1030  0.121  136.727  265987.0
40 -0.000441 -0.000278 -0.001458 -0.000920  ...  0.1020  0.427  147.941  233514.0
41  0.001177  0.002950 -0.000194 -0.000059  ...  0.0506  0.596   95.003  202105.0
42  0.001177  0.002950 -0.000194 -0.000059  ...  0.3340  0.634   94.987  244540.0
43 -0.002030  0.001467  0.001902  0.000422  ...  0.1160  0.102   75.101  313360.0
44 -0.001218 -0.002350 -0.002041  0.002774  ...  0.1460  0.289  144.018  211667.0
45 -0.001505 -0.003268  0.002726 -0.001058  ...  0.0614  0.398  102.024  235588.0
46  0.002402  0.003219 -0.001280  0.003429  ...  0.0800  0.923  140.042  234857.0
47  0.002964 -0.001297  0.002941 -0.001433  ...  0.0785  0.319  128.261  

## Models:
evaluated by f1 score and accuracy for 10 folds

## Light GBM:

In [ ]:
import time
import lightgbm as lgbm
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import log_loss, f1_score, accuracy_score


def train_LightGBM(X, y):

  N_SPLITS = 10
  strat_kf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

  LOSS = np.empty(N_SPLITS)
  f1_SCORE = np.empty(N_SPLITS)
  Accuracy = np.empty(N_SPLITS)

  for idx, (train_idx, test_idx) in enumerate(strat_kf.split(X, y)):
      print("=" * 12 + f"Training fold {idx+1}" + 12 * "=")
      start = time.time()

      X_train, X_val = X.iloc[train_idx], X.iloc[test_idx]
      y_train, y_val = y[train_idx], y[test_idx]
      eval_set = [(X_val, y_val)]

      lgbm_clf = lgbm.LGBMClassifier(n_estimators=10000)
      lgbm_clf.fit(
          X_train,
          y_train,
          eval_set=eval_set,
          early_stopping_rounds=200,
          eval_metric="binary_logloss",
          verbose=False,
      )

      pickle.dump(lgbm_clf, open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/Models/saved_models/LightGBM/lightgbm_model_%s.pickle' % str(idx+1), 'wb'))

      preds = lgbm_clf.predict_proba(X_val)
      loss = log_loss(y_val, preds)
      LOSS[idx] = loss

      print(np.argmax(preds, axis=-1))
      f1 = f1_score(y_val.tolist(), np.argmax(preds, axis=-1))
      f1_SCORE[idx] = f1

      acc = accuracy_score(y_val.tolist(), np.argmax(preds, axis=-1))
      Accuracy[idx] = acc
      runtime = time.time() - start
      print(f"Fold {idx+1} finished with loss: {loss:.5f} in {runtime:.2f} seconds.\n")
      print(f"Fold {idx+1} finished with f1 score: {f1:.5f} in {runtime:.2f} seconds.\n")
      print(f"Fold {idx+1} finished with accuracy: {acc:.5f} in {runtime:.2f} seconds.\n")

  print(f'Average f1 score of {N_SPLITS} folds: {np.mean(f1_SCORE, axis=0)}')
  print(f'Average accuracy of {N_SPLITS} folds: {np.mean(Accuracy, axis=0)}')

In [ ]:
# user 1
X = user1_X_train
y = user1_train_csv['label']
train_LightGBM(X, y)

============Training fold 1============
[0 1 0 0 0 0]
Fold 1 finished with loss: 0.00004 in 0.84 seconds.

Fold 1 finished with f1 score: 1.00000 in 0.84 seconds.

Fold 1 finished with accuracy: 1.00000 in 0.84 seconds.

============Training fold 2============
[0 1 0 0 1 0]
Fold 2 finished with loss: 0.00097 in 0.42 seconds.

Fold 2 finished with f1 score: 1.00000 in 0.42 seconds.

Fold 2 finished with accuracy: 1.00000 in 0.42 seconds.

============Training fold 3============
[0 0 1 0 1 0]
Fold 3 finished with loss: 0.00129 in 0.51 seconds.

Fold 3 finished with f1 score: 1.00000 in 0.51 seconds.

Fold 3 finished with accuracy: 1.00000 in 0.51 seconds.

============Training fold 4============
[0 0 1 0 1 0]
Fold 4 finished with loss: 0.00056 in 0.56 seconds.

Fold 4 finished with f1 score: 1.00000 in 0.56 seconds.

Fold 4 finished with accuracy: 1.00000 in 0.56 seconds.

============Training fold 5============
[0 1 0 0 0 1]
Fold 5 finished with loss: 0.00013 in 0.46 seconds.

Fold 5 fi

In [ ]:
# user 2
X = user2_X_train
y = user2_train_csv['label']
train_LightGBM(X, y)

============Training fold 1============
[0 0 0 1 0 0 0 0 1 1 0 0]
Fold 1 finished with loss: 0.41812 in 0.13 seconds.

Fold 1 finished with f1 score: 0.85714 in 0.13 seconds.

Fold 1 finished with accuracy: 0.91667 in 0.13 seconds.

============Training fold 2============
[0 0 1 0 0 0 1 0 1 0 1 0]
Fold 2 finished with loss: 0.00020 in 0.18 seconds.

Fold 2 finished with f1 score: 1.00000 in 0.18 seconds.

Fold 2 finished with accuracy: 1.00000 in 0.18 seconds.

============Training fold 3============
[0 0 0 0 0 1 1 1 1 0 0 0]
Fold 3 finished with loss: 0.00004 in 0.18 seconds.

Fold 3 finished with f1 score: 1.00000 in 0.18 seconds.

Fold 3 finished with accuracy: 1.00000 in 0.18 seconds.

============Training fold 4============
[0 0 1 1 0 1 0 1 0 0 0 1]
Fold 4 finished with loss: 0.13696 in 0.19 seconds.

Fold 4 finished with f1 score: 0.88889 in 0.19 seconds.

Fold 4 finished with accuracy: 0.91667 in 0.19 seconds.

============Training fold 5============
[0 0 1 0 0 1 0 0 1 1 0 0]
Fo

In [ ]:
# user 3
X = user3_X_train
y = user3_train_csv['label']
train_LightGBM(X, y)

============Training fold 1============
[0 0 0 0 0 0 0 0]
Fold 1 finished with loss: 0.66723 in 0.10 seconds.

Fold 1 finished with f1 score: 0.00000 in 0.10 seconds.

Fold 1 finished with accuracy: 0.62500 in 0.10 seconds.

============Training fold 2============
[1 0 0 0 1 0 0 0]
Fold 2 finished with loss: 0.60693 in 0.11 seconds.

Fold 2 finished with f1 score: 0.40000 in 0.11 seconds.

Fold 2 finished with accuracy: 0.62500 in 0.11 seconds.

============Training fold 3============
[0 0 0 0 0 0 0 0]
Fold 3 finished with loss: 0.64684 in 0.09 seconds.

Fold 3 finished with f1 score: 0.00000 in 0.09 seconds.

Fold 3 finished with accuracy: 0.62500 in 0.09 seconds.

============Training fold 4============
[0 0 0 0 0 0 0 0]
Fold 4 finished with loss: 0.48079 in 0.14 seconds.

Fold 4 finished with f1 score: 0.00000 in 0.14 seconds.

Fold 4 finished with accuracy: 0.62500 in 0.14 seconds.

============Training fold 5============
[0 0 0 1 0 0 0 0]
Fold 5 finished with loss: 0.51201 in 0.12

## Logistic regression

In [ ]:
import pickle
from sklearn.linear_model import LogisticRegression


def train_LogReg(X, y):
  N_SPLITS = 10
  strat_kf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

  LOSS = np.empty(N_SPLITS)
  f1_SCORE = np.empty(N_SPLITS)
  Accuracy = np.empty(N_SPLITS)

  for idx, (train_idx, test_idx) in enumerate(strat_kf.split(X, y)):
      print("=" * 12 + f"Training fold {idx+1}" + 12 * "=")
      start = time.time()

      X_train, X_val = X.iloc[train_idx], X.iloc[test_idx]
      y_train, y_val = y[train_idx], y[test_idx]
      eval_set = [(X_val, y_val)]

      # create model
      LogReg = LogisticRegression()

      LogReg.fit(
          X_train,
          y_train)
      
      filename = '/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/Models/saved_models/Logistic_Regression/LogisticReg_model_%s.pkl' % str(idx+1)
      pickle.dump(LogReg, open(filename, 'wb'))

      preds = LogReg.predict_proba(X_val)
      loss = log_loss(y_val, preds)
      LOSS[idx] = loss

      f1 = f1_score(y_val.tolist(), np.argmax(preds, axis=-1))
      f1_SCORE[idx] = f1

      acc = accuracy_score(y_val.tolist(), np.argmax(preds, axis=-1))
      Accuracy[idx] = acc
      runtime = time.time() - start
      print(f"Fold {idx+1} finished with loss: {loss:.5f} in {runtime:.2f} seconds.\n")
      print(f"Fold {idx+1} finished with f1 score: {f1:.5f} in {runtime:.2f} seconds.\n")
      print(f"Fold {idx+1} finished with accuracy: {acc:.5f} in {runtime:.2f} seconds.\n")

  print(f'Average f1 score of {N_SPLITS} folds: {np.mean(f1_SCORE, axis=0)}')
  print(f'Average accuracy of {N_SPLITS} folds: {np.mean(Accuracy, axis=0)}')

In [ ]:
# user 1
X = user1_X_train
y = user1_train_csv['label']
train_LogReg(X, y)

============Training fold 1============
Fold 1 finished with loss: 0.59539 in 0.65 seconds.

Fold 1 finished with f1 score: 0.00000 in 0.65 seconds.

Fold 1 finished with accuracy: 0.66667 in 0.65 seconds.

============Training fold 2============
Fold 2 finished with loss: 0.20795 in 0.33 seconds.

Fold 2 finished with f1 score: 1.00000 in 0.33 seconds.

Fold 2 finished with accuracy: 1.00000 in 0.33 seconds.

============Training fold 3============
Fold 3 finished with loss: 0.50905 in 0.39 seconds.

Fold 3 finished with f1 score: 0.80000 in 0.39 seconds.

Fold 3 finished with accuracy: 0.83333 in 0.39 seconds.

============Training fold 4============
Fold 4 finished with loss: 0.35211 in 0.37 seconds.

Fold 4 finished with f1 score: 1.00000 in 0.37 seconds.

Fold 4 finished with accuracy: 1.00000 in 0.37 seconds.

============Training fold 5============
Fold 5 finished with loss: 1.03399 in 0.37 seconds.

Fold 5 finished with f1 score: 0.00000 in 0.37 seconds.

Fold 5 finished with a

In [ ]:
# user 2
X = user2_X_train
y = user2_train_csv['label']
train_LogReg(X, y)

============Training fold 1============
Fold 1 finished with loss: 0.56660 in 0.03 seconds.

Fold 1 finished with f1 score: 0.66667 in 0.03 seconds.

Fold 1 finished with accuracy: 0.75000 in 0.03 seconds.

============Training fold 2============
Fold 2 finished with loss: 0.55734 in 0.03 seconds.

Fold 2 finished with f1 score: 0.40000 in 0.03 seconds.

Fold 2 finished with accuracy: 0.75000 in 0.03 seconds.

============Training fold 3============
Fold 3 finished with loss: 0.60085 in 0.03 seconds.

Fold 3 finished with f1 score: 0.50000 in 0.03 seconds.

Fold 3 finished with accuracy: 0.66667 in 0.03 seconds.

============Training fold 4============
Fold 4 finished with loss: 0.61495 in 0.02 seconds.

Fold 4 finished with f1 score: 0.00000 in 0.02 seconds.

Fold 4 finished with accuracy: 0.66667 in 0.02 seconds.

============Training fold 5============
Fold 5 finished with loss: 1.05470 in 0.03 seconds.

Fold 5 finished with f1 score: 0.00000 in 0.03 seconds.

Fold 5 finished with a

In [ ]:
# user 3
X = user3_X_train
y = user3_train_csv['label']
train_LogReg(X, y)

============Training fold 1============
Fold 1 finished with loss: 0.79584 in 0.05 seconds.

Fold 1 finished with f1 score: 0.00000 in 0.05 seconds.

Fold 1 finished with accuracy: 0.50000 in 0.05 seconds.

============Training fold 2============
Fold 2 finished with loss: 0.99417 in 0.03 seconds.

Fold 2 finished with f1 score: 0.00000 in 0.03 seconds.

Fold 2 finished with accuracy: 0.37500 in 0.03 seconds.

============Training fold 3============
Fold 3 finished with loss: 0.69193 in 0.02 seconds.

Fold 3 finished with f1 score: 0.00000 in 0.02 seconds.

Fold 3 finished with accuracy: 0.62500 in 0.02 seconds.

============Training fold 4============
Fold 4 finished with loss: 0.69441 in 0.03 seconds.

Fold 4 finished with f1 score: 0.00000 in 0.03 seconds.

Fold 4 finished with accuracy: 0.62500 in 0.03 seconds.

============Training fold 5============
Fold 5 finished with loss: 0.58989 in 0.03 seconds.

Fold 5 finished with f1 score: 0.00000 in 0.03 seconds.

Fold 5 finished with a

## SVM

In [ ]:
import pickle
from sklearn import svm
from sklearn.svm import LinearSVC
from statistics import mean



def train_SVM(X, y):
  N_SPLITS = 10
  strat_kf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

  LOSS = np.empty(N_SPLITS)
  f1_SCORE = np.empty(N_SPLITS)
  Accuracy = np.empty(N_SPLITS)

  for idx, (train_idx, test_idx) in enumerate(strat_kf.split(X, y)):
      print("=" * 12 + f"Training fold {idx+1}" + 12 * "=")
      start = time.time()

      X_train, X_val = X.iloc[train_idx], X.iloc[test_idx]
      y_train, y_val = y[train_idx], y[test_idx]
      eval_set = [(X_val, y_val)]

      # create model
      model = svm.SVC(kernel='linear', C=1, random_state=10)

      model.fit(
          X_train,
          y_train)
      
      filename = '/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/Models/saved_models/SVM/SVM_model_%s.pkl' % str(idx+1)
      pickle.dump(model, open(filename, 'wb'))

      preds = model.predict(X_val)
      print(preds)
      loss = log_loss(y_val, preds)
      LOSS[idx] = loss

      f1 = f1_score(y_val.tolist(), preds)
      f1_SCORE[idx] = f1

      acc = accuracy_score(y_val.tolist(), preds)
      Accuracy[idx] = acc
      runtime = time.time() - start
      print(f"Fold {idx+1} finished with loss: {loss:.5f} in {runtime:.2f} seconds.\n")
      print(f"Fold {idx+1} finished with f1 score: {f1:.5f} in {runtime:.2f} seconds.\n")
      print(f"Fold {idx+1} finished with accuracy: {acc:.5f} in {runtime:.2f} seconds.\n")

  print(f'Average f1 score of {N_SPLITS} folds: {mean(f1_SCORE)}')
  print(f'Average accuracy of {N_SPLITS} folds: {mean(Accuracy)}')

In [ ]:
# user 1
X = user1_X_train
y = user1_train_csv['label']
train_SVM(X, y)

============Training fold 1============
[0 0 0 0 0 0]
Fold 1 finished with loss: 5.75646 in 1.56 seconds.

Fold 1 finished with f1 score: 0.00000 in 1.56 seconds.

Fold 1 finished with accuracy: 0.83333 in 1.56 seconds.

============Training fold 2============
[0 0 0 0 0 0]
Fold 2 finished with loss: 11.51293 in 1.40 seconds.

Fold 2 finished with f1 score: 0.00000 in 1.40 seconds.

Fold 2 finished with accuracy: 0.66667 in 1.40 seconds.

============Training fold 3============
[0 1 1 1 0 0]
Fold 3 finished with loss: 17.26965 in 0.86 seconds.

Fold 3 finished with f1 score: 0.40000 in 0.86 seconds.

Fold 3 finished with accuracy: 0.50000 in 0.86 seconds.

============Training fold 4============
[1 0 1 0 0 0]
Fold 4 finished with loss: 11.51306 in 0.77 seconds.

Fold 4 finished with f1 score: 0.50000 in 0.77 seconds.

Fold 4 finished with accuracy: 0.66667 in 0.77 seconds.

============Training fold 5============
[0 0 0 0 0 0]
Fold 5 finished with loss: 11.51293 in 5.08 seconds.

Fold 

In [ ]:
# user 2
X = user2_X_train
y = user2_train_csv['label']
train_SVM(X, y)

============Training fold 1============
[0 0 0 0 0 0 1 0 0 0 0 0]
Fold 1 finished with loss: 14.39122 in 1.51 seconds.

Fold 1 finished with f1 score: 0.00000 in 1.51 seconds.

Fold 1 finished with accuracy: 0.58333 in 1.51 seconds.

============Training fold 2============
[0 0 0 0 0 0 0 0 0 0 1 0]
Fold 2 finished with loss: 8.63469 in 4.17 seconds.

Fold 2 finished with f1 score: 0.40000 in 4.17 seconds.

Fold 2 finished with accuracy: 0.75000 in 4.17 seconds.

============Training fold 3============
[0 0 0 0 0 0 0 0 0 0 0 0]
Fold 3 finished with loss: 11.51293 in 3.36 seconds.

Fold 3 finished with f1 score: 0.00000 in 3.36 seconds.

Fold 3 finished with accuracy: 0.66667 in 3.36 seconds.

============Training fold 4============
[0 0 0 0 0 0 0 1 0 0 0 1]
Fold 4 finished with loss: 11.51299 in 9.70 seconds.

Fold 4 finished with f1 score: 0.33333 in 9.70 seconds.

Fold 4 finished with accuracy: 0.66667 in 9.70 seconds.

============Training fold 5============
[0 0 0 0 0 0 0 0 0 0 0 1]

In [ ]:
# user 3
X = user3_X_train
y = user3_train_csv['label']
train_SVM(X, y)

============Training fold 1============
[0 0 0 0 0 0 0 0]
Fold 1 finished with loss: 12.95204 in 1.08 seconds.

Fold 1 finished with f1 score: 0.00000 in 1.08 seconds.

Fold 1 finished with accuracy: 0.62500 in 1.08 seconds.

============Training fold 2============
[0 0 0 0 0 0 0 0]
Fold 2 finished with loss: 12.95204 in 1.28 seconds.

Fold 2 finished with f1 score: 0.00000 in 1.28 seconds.

Fold 2 finished with accuracy: 0.62500 in 1.28 seconds.

============Training fold 3============
[0 0 0 0 0 0 0 0]
Fold 3 finished with loss: 12.95204 in 13.19 seconds.

Fold 3 finished with f1 score: 0.00000 in 13.19 seconds.

Fold 3 finished with accuracy: 0.62500 in 13.19 seconds.

============Training fold 4============
[0 0 0 0 0 0 0 0]
Fold 4 finished with loss: 12.95204 in 4.10 seconds.

Fold 4 finished with f1 score: 0.00000 in 4.10 seconds.

Fold 4 finished with accuracy: 0.62500 in 4.10 seconds.

============Training fold 5============
[0 0 0 0 0 0 0 0]
Fold 5 finished with loss: 12.95204

## Boosting decision tree

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import log_loss, f1_score, accuracy_score
import pickle
import time



def train_BoostingDT(X, y):
  N_SPLITS = 10
  strat_kf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

  LOSS = np.empty(N_SPLITS)
  f1_SCORE = np.empty(N_SPLITS)
  Accuracy = np.empty(N_SPLITS)

  for idx, (train_idx, test_idx) in enumerate(strat_kf.split(X, y)):
      print("=" * 12 + f"Training fold {idx+1}" + 12 * "=")
      start = time.time()

      X_train, X_val = X.iloc[train_idx], X.iloc[test_idx]
      y_train, y_val = y[train_idx], y[test_idx]
      eval_set = [(X_val, y_val)]

      # create model
      BoostingDT = AdaBoostClassifier(DecisionTreeClassifier(min_samples_split=10,max_depth=4),n_estimators=10,learning_rate=0.6)

      BoostingDT.fit(
          X_train,
          y_train)
      
      filename = '/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/Models/saved_models/BoostingDT/BoostingDecisionTree_model_%s.pkl' % str(idx+1)
      pickle.dump(BoostingDT, open(filename, 'wb'))

      preds = BoostingDT.predict_proba(X_val)
      loss = log_loss(y_val, preds)
      LOSS[idx] = loss

      f1 = f1_score(y_val.tolist(), np.argmax(preds, axis=-1))
      f1_SCORE[idx] = f1

      acc = accuracy_score(y_val.tolist(), np.argmax(preds, axis=-1))
      Accuracy[idx] = acc
      runtime = time.time() - start
      print(f"Fold {idx+1} finished with loss: {loss:.5f} in {runtime:.2f} seconds.\n")
      print(f"Fold {idx+1} finished with f1 score: {f1:.5f} in {runtime:.2f} seconds.\n")
      print(f"Fold {idx+1} finished with accuracy: {acc:.5f} in {runtime:.2f} seconds.\n")

  print(f'Average f1 score of {N_SPLITS} folds: {np.mean(f1_SCORE, axis=0)}')
  print(f'Average accuracy of {N_SPLITS} folds: {np.mean(Accuracy, axis=0)}')

In [ ]:
# user 1
X = user1_X_train
y = user1_train_csv['label']
train_BoostingDT(X, y)

============Training fold 1============
Fold 1 finished with loss: 0.00000 in 0.87 seconds.

Fold 1 finished with f1 score: 1.00000 in 0.87 seconds.

Fold 1 finished with accuracy: 1.00000 in 0.87 seconds.

============Training fold 2============
Fold 2 finished with loss: 0.00000 in 0.47 seconds.

Fold 2 finished with f1 score: 1.00000 in 0.47 seconds.

Fold 2 finished with accuracy: 1.00000 in 0.47 seconds.

============Training fold 3============
Fold 3 finished with loss: 0.00000 in 0.29 seconds.

Fold 3 finished with f1 score: 1.00000 in 0.29 seconds.

Fold 3 finished with accuracy: 1.00000 in 0.29 seconds.

============Training fold 4============
Fold 4 finished with loss: 5.75646 in 0.59 seconds.

Fold 4 finished with f1 score: 0.80000 in 0.59 seconds.

Fold 4 finished with accuracy: 0.83333 in 0.59 seconds.

============Training fold 5============
Fold 5 finished with loss: 0.00000 in 0.35 seconds.

Fold 5 finished with f1 score: 1.00000 in 0.35 seconds.

Fold 5 finished with a

In [ ]:
# user 2
X = user2_X_train
y = user2_train_csv['label']
train_BoostingDT(X, y)

============Training fold 1============
Fold 1 finished with loss: 5.75646 in 0.02 seconds.

Fold 1 finished with f1 score: 0.75000 in 0.02 seconds.

Fold 1 finished with accuracy: 0.83333 in 0.02 seconds.

============Training fold 2============
Fold 2 finished with loss: 2.87823 in 0.02 seconds.

Fold 2 finished with f1 score: 0.88889 in 0.02 seconds.

Fold 2 finished with accuracy: 0.91667 in 0.02 seconds.

============Training fold 3============
Fold 3 finished with loss: 2.87823 in 0.02 seconds.

Fold 3 finished with f1 score: 0.88889 in 0.02 seconds.

Fold 3 finished with accuracy: 0.91667 in 0.02 seconds.

============Training fold 4============
Fold 4 finished with loss: 0.00000 in 0.02 seconds.

Fold 4 finished with f1 score: 1.00000 in 0.02 seconds.

Fold 4 finished with accuracy: 1.00000 in 0.02 seconds.

============Training fold 5============
Fold 5 finished with loss: 2.87823 in 0.02 seconds.

Fold 5 finished with f1 score: 0.85714 in 0.02 seconds.

Fold 5 finished with a

In [ ]:
# user 3
X = user3_X_train
y = user3_train_csv['label']
train_BoostingDT(X, y)

============Training fold 1============
Fold 1 finished with loss: 5.51027 in 0.10 seconds.

Fold 1 finished with f1 score: 0.00000 in 0.10 seconds.

Fold 1 finished with accuracy: 0.62500 in 0.10 seconds.

============Training fold 2============
Fold 2 finished with loss: 9.13677 in 0.09 seconds.

Fold 2 finished with f1 score: 0.00000 in 0.09 seconds.

Fold 2 finished with accuracy: 0.50000 in 0.09 seconds.

============Training fold 3============
Fold 3 finished with loss: 4.24137 in 0.09 seconds.

Fold 3 finished with f1 score: 0.00000 in 0.09 seconds.

Fold 3 finished with accuracy: 0.50000 in 0.09 seconds.

============Training fold 4============
Fold 4 finished with loss: 17.26939 in 0.02 seconds.

Fold 4 finished with f1 score: 0.33333 in 0.02 seconds.

Fold 4 finished with accuracy: 0.50000 in 0.02 seconds.

============Training fold 5============
Fold 5 finished with loss: 1.52752 in 0.09 seconds.

Fold 5 finished with f1 score: 0.40000 in 0.09 seconds.

Fold 5 finished with 

# Evaluation on test set:


In [ ]:
user1_test_csv = pd.read_csv('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/user1/user1_test.csv')
user2_test_csv = pd.read_csv('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/user2/user2_test.csv')
user3_test_csv = pd.read_csv('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/user3/user3_test.csv')

In [ ]:

# Define the function to remove the punctuation
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text

def handle_text(text):
  #remove punctuation:
  temp = remove_punctuations(text)

  #word tokenize:
  temp = ViTokenizer.tokenize(temp)

  #lowercase:
  temp = temp.lower()

  return temp


def get_artist_trackname_vector(user1_csv):

  user1_artist_trackname = []

  for i in range(len(user1_csv)):
    artist_vector = model.wv[[item for item in handle_text(user1_csv['artists'][i]).split()]]
    artist_vector = np.mean(artist_vector, axis=0)

    track_name_vector = model.wv[[item for item in handle_text(user1_csv['track_name'][i]).split()]]
    track_name_vector = np.mean(track_name_vector, axis=0)

    general = np.concatenate((artist_vector, track_name_vector), axis=0)
    user1_artist_trackname.append(general)
  return user1_artist_trackname

def get_DIGITAL_FEATURE(user1_csv):
  DIGITAL_FEATURE = []
  for i in range(len(user1_csv)):
    digital_feature = []
    for feature in features:
      digital_feature.append(user1_csv[feature][i])
    DIGITAL_FEATURE.append(digital_feature)

  return DIGITAL_FEATURE



def get_artist_trackname_vector(user1_csv):
  model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/Models/saved_models/w2v.pickle', 'rb'))
  user1_artist_trackname = []

  for i in range(len(user1_csv)):
    try:
      artist_vector = model.wv[[item for item in handle_text(user1_csv['artists'][i]).split()]]
    except:
      artist_vector = model.wv[[item for item in handle_text('unk').split()]]
    artist_vector = np.mean(artist_vector, axis=0)

    try:
      track_name_vector = model.wv[[item for item in handle_text(user1_csv['track_name'][i]).split()]]
    except:
      track_name_vector = model.wv[[item for item in handle_text('unk').split()]]
    track_name_vector = np.mean(track_name_vector, axis=0)

    general = np.concatenate((artist_vector, track_name_vector), axis=0)
    user1_artist_trackname.append(general)
  return user1_artist_trackname


def get_general_feature(df_user1):
  general_feature = []
  for i in range(len(df_user1)):
    temp = np.concatenate((df_user1['artist_trackname'][i], df_user1['DIGITAL_FEATURE'][i]), axis=0)
    general_feature.append(temp)

  return general_feature  

def get_X(user1_general_feature):
  X = []
  for general_feature in user1_general_feature:  
    temp = general_feature.tolist()
    X.append(temp)

  return pd.DataFrame(X)

features = ['popularity', 'danceability', 'energy', 'key', 'loudness', 'mode',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms']

In [ ]:
user1_test_DIGITAL_FEATURE = get_DIGITAL_FEATURE(user1_test_csv)
user2_test_DIGITAL_FEATURE = get_DIGITAL_FEATURE(user2_test_csv)
user3_test_DIGITAL_FEATURE = get_DIGITAL_FEATURE(user3_test_csv)

user1_test_artist_trackname = get_artist_trackname_vector(user1_test_csv)
user2_test_artist_trackname = get_artist_trackname_vector(user2_test_csv)
user3_test_artist_trackname = get_artist_trackname_vector(user3_test_csv)

df_user1_test = pd.DataFrame()
df_user1_test['artist_trackname'] = user1_test_artist_trackname
df_user1_test['DIGITAL_FEATURE'] = user1_test_DIGITAL_FEATURE

df_user2_test = pd.DataFrame()
df_user2_test['artist_trackname'] = user2_test_artist_trackname
df_user2_test['DIGITAL_FEATURE'] = user2_test_DIGITAL_FEATURE

df_user3_test = pd.DataFrame()
df_user3_test['artist_trackname'] = user3_test_artist_trackname
df_user3_test['DIGITAL_FEATURE'] = user3_test_DIGITAL_FEATURE


user1_test_general_feature =  get_general_feature(df_user1_test)
user2_test_general_feature =  get_general_feature(df_user2_test)
user3_test_general_feature =  get_general_feature(df_user3_test)

user1_X_test = get_X(user1_test_general_feature)
user2_X_test = get_X(user2_test_general_feature)
user3_X_test = get_X(user3_test_general_feature)

user1_y_test = user1_test_csv['label']
user2_y_test = user2_test_csv['label']
user3_y_test = user3_test_csv['label']

In [ ]:
# LightGBM
f1_SCORE = np.empty(10)
Accuracy = np.empty(10)
for i in range(10):
    model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/Models/saved_models/LightGBM/lightgbm_model_%s.pickle' % str(i+1), 'rb'))
    preds = model.predict_proba(user1_X_test)

    f1 = f1_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
    f1_SCORE[i] = f1

    acc = accuracy_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
    Accuracy[i] = acc

    print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
    print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

Fold 1 model has f1 score: 0.00000

Fold 1 model has accuracy: 0.50000

Fold 2 model has f1 score: 0.00000

Fold 2 model has accuracy: 0.50000

Fold 3 model has f1 score: 0.00000

Fold 3 model has accuracy: 0.50000

Fold 4 model has f1 score: 0.90909

Fold 4 model has accuracy: 0.90000

Fold 5 model has f1 score: 0.50000

Fold 5 model has accuracy: 0.60000

Fold 6 model has f1 score: 0.00000

Fold 6 model has accuracy: 0.50000

Fold 7 model has f1 score: 0.00000

Fold 7 model has accuracy: 0.50000

Fold 8 model has f1 score: 0.00000

Fold 8 model has accuracy: 0.40000

Fold 9 model has f1 score: 0.28571

Fold 9 model has accuracy: 0.50000

Fold 10 model has f1 score: 0.00000

Fold 10 model has accuracy: 0.50000

Average f1 score of 10 folds: 0.1694805194805195
Average accuracy of 10 folds: 0.54


In [ ]:
# Logistic Regression
f1_SCORE = np.empty(10)
Accuracy = np.empty(10)
for i in range(10):
    model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/Models/saved_models/Logistic_Regression/LogisticReg_model_%s.pkl' % str(i+1), 'rb'))
    preds = model.predict_proba(user1_X_test)

    f1 = f1_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
    f1_SCORE[i] = f1

    acc = accuracy_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
    Accuracy[i] = acc

    print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
    print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

Fold 1 model has f1 score: 0.00000

Fold 1 model has accuracy: 0.50000

Fold 2 model has f1 score: 0.00000

Fold 2 model has accuracy: 0.50000

Fold 3 model has f1 score: 0.00000

Fold 3 model has accuracy: 0.50000

Fold 4 model has f1 score: 0.00000

Fold 4 model has accuracy: 0.50000

Fold 5 model has f1 score: 0.00000

Fold 5 model has accuracy: 0.50000

Fold 6 model has f1 score: 0.00000

Fold 6 model has accuracy: 0.50000

Fold 7 model has f1 score: 0.00000

Fold 7 model has accuracy: 0.50000

Fold 8 model has f1 score: 0.00000

Fold 8 model has accuracy: 0.50000

Fold 9 model has f1 score: 0.00000

Fold 9 model has accuracy: 0.50000

Fold 10 model has f1 score: 0.00000

Fold 10 model has accuracy: 0.50000

Average f1 score of 10 folds: 0.0
Average accuracy of 10 folds: 0.5


In [ ]:
# SVM
f1_SCORE = np.empty(10)
Accuracy = np.empty(10)
for i in range(10):
    model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/Models/saved_models/SVM/SVM_model_%s.pkl' % str(i+1), 'rb'))
    preds = model.predict(user1_X_test)

    f1 = f1_score(user1_y_test.tolist(), preds)
    f1_SCORE[i] = f1

    acc = accuracy_score(user1_y_test.tolist(), preds)
    Accuracy[i] = acc

    print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
    print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

Fold 1 model has f1 score: 0.00000

Fold 1 model has accuracy: 0.50000

Fold 2 model has f1 score: 0.00000

Fold 2 model has accuracy: 0.50000

Fold 3 model has f1 score: 0.00000

Fold 3 model has accuracy: 0.50000

Fold 4 model has f1 score: 0.00000

Fold 4 model has accuracy: 0.50000

Fold 5 model has f1 score: 0.00000

Fold 5 model has accuracy: 0.50000

Fold 6 model has f1 score: 0.00000

Fold 6 model has accuracy: 0.50000

Fold 7 model has f1 score: 0.00000

Fold 7 model has accuracy: 0.50000

Fold 8 model has f1 score: 0.00000

Fold 8 model has accuracy: 0.50000

Fold 9 model has f1 score: 0.00000

Fold 9 model has accuracy: 0.50000

Fold 10 model has f1 score: 0.00000

Fold 10 model has accuracy: 0.50000

Average f1 score of 10 folds: 0.0
Average accuracy of 10 folds: 0.5


## predict_user:

In [ ]:
def predict_user1(user1_test_csv):
  user1_test_DIGITAL_FEATURE = get_DIGITAL_FEATURE(user1_test_csv)

  user1_test_artist_trackname = get_artist_trackname_vector(user1_test_csv)

  df_user1_test = pd.DataFrame()
  df_user1_test['artist_trackname'] = user1_test_artist_trackname
  df_user1_test['DIGITAL_FEATURE'] = user1_test_DIGITAL_FEATURE

  user1_test_general_feature =  get_general_feature(df_user1_test)

  user1_X_test = get_X(user1_test_general_feature)

  temp = input('select a model: 1.LightGBM, 2.Logistic Regression, 3.SVM, 4.BoostingDT\n')
  temp = int(temp)
  
  if temp == 1:
    # LightGBM
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/LightGBM_user1/lightgbm_model_%s.pickle' % str(i+1), 'rb'))
        preds = model.predict_proba(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

  if temp == 2:
    # Logistic Regression
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/Logistic_Regression_user1/LogisticReg_model_%s.pkl' % str(i+1), 'rb'))
        preds = model.predict_proba(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

  if temp == 3:
    # SVM
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/SVM_user1/SVM_model_%s.pkl' % str(i+1), 'rb'))
        preds = model.predict(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), preds)
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), preds)
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

  if temp == 4:
    # Boosting Decision Tree
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/BoostingDT_user1/BoostingDecisionTree_model_%s.pkl' % str(i+1), 'rb'))
        preds = model.predict(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), preds)
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), preds)
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')



In [ ]:
predict_user1(user1_test_csv)

select a model: 1.LightGBM, 2.Logistic Regression, 3.SVM, 4.BoostingDT
3
Fold 1 model has f1 score: 0.33333

Fold 1 model has accuracy: 0.60000

Fold 2 model has f1 score: 0.00000

Fold 2 model has accuracy: 0.50000

Fold 3 model has f1 score: 0.50000

Fold 3 model has accuracy: 0.60000

Fold 4 model has f1 score: 0.50000

Fold 4 model has accuracy: 0.60000

Fold 5 model has f1 score: 0.00000

Fold 5 model has accuracy: 0.50000

Fold 6 model has f1 score: 0.33333

Fold 6 model has accuracy: 0.60000

Fold 7 model has f1 score: 0.50000

Fold 7 model has accuracy: 0.60000

Fold 8 model has f1 score: 0.33333

Fold 8 model has accuracy: 0.60000

Fold 9 model has f1 score: 0.00000

Fold 9 model has accuracy: 0.50000

Fold 10 model has f1 score: 0.00000

Fold 10 model has accuracy: 0.50000

Average f1 score of 10 folds: 0.25
Average accuracy of 10 folds: 0.5599999999999999


In [ ]:
def predict_user2(user2_test_csv):
  user1_test_DIGITAL_FEATURE = get_DIGITAL_FEATURE(user2_test_csv)

  user1_test_artist_trackname = get_artist_trackname_vector(user2_test_csv)

  df_user1_test = pd.DataFrame()
  df_user1_test['artist_trackname'] = user1_test_artist_trackname
  df_user1_test['DIGITAL_FEATURE'] = user1_test_DIGITAL_FEATURE

  user1_test_general_feature =  get_general_feature(df_user1_test)

  user1_X_test = get_X(user1_test_general_feature)

  temp = input('select a model: 1.LightGBM, 2.Logistic Regression, 3.SVM, 4.BoostingDT\n')
  temp = int(temp)
  
  if temp == 1:
    # LightGBM
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/LightGBM_user2/lightgbm_model_%s.pickle' % str(i+1), 'rb'))
        preds = model.predict_proba(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

  if temp == 2:
    # Logistic Regression
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/Logistic_Regression_user2/LogisticReg_model_%s.pkl' % str(i+1), 'rb'))
        preds = model.predict_proba(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

  if temp == 3:
    # SVM
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/SVM_user2/SVM_model_%s.pkl' % str(i+1), 'rb'))
        preds = model.predict(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), preds)
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), preds)
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

  if temp == 4:
    # Boosting Decision Tree
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/BoostingDT_user2/BoostingDecisionTree_model_%s.pkl' % str(i+1), 'rb'))
        preds = model.predict(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), preds)
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), preds)
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')



In [ ]:
predict_user2(user2_test_csv)

select a model: 1.LightGBM, 2.Logistic Regression, 3.SVM, 4.BoostingDT
4
Fold 1 model has f1 score: 0.00000

Fold 1 model has accuracy: 0.50000

Fold 2 model has f1 score: 0.00000

Fold 2 model has accuracy: 0.50000

Fold 3 model has f1 score: 0.00000

Fold 3 model has accuracy: 0.30000

Fold 4 model has f1 score: 0.00000

Fold 4 model has accuracy: 0.50000

Fold 5 model has f1 score: 0.00000

Fold 5 model has accuracy: 0.50000

Fold 6 model has f1 score: 0.00000

Fold 6 model has accuracy: 0.50000

Fold 7 model has f1 score: 0.00000

Fold 7 model has accuracy: 0.30000

Fold 8 model has f1 score: 0.00000

Fold 8 model has accuracy: 0.50000

Fold 9 model has f1 score: 0.00000

Fold 9 model has accuracy: 0.50000

Fold 10 model has f1 score: 0.00000

Fold 10 model has accuracy: 0.50000

Average f1 score of 10 folds: 0.0
Average accuracy of 10 folds: 0.45999999999999996


In [ ]:
def predict_user3(user3_test_csv):
  user1_test_DIGITAL_FEATURE = get_DIGITAL_FEATURE(user3_test_csv)

  user1_test_artist_trackname = get_artist_trackname_vector(user3_test_csv)

  df_user1_test = pd.DataFrame()
  df_user1_test['artist_trackname'] = user1_test_artist_trackname
  df_user1_test['DIGITAL_FEATURE'] = user1_test_DIGITAL_FEATURE

  user1_test_general_feature =  get_general_feature(df_user1_test)

  user1_X_test = get_X(user1_test_general_feature)

  temp = input('select a model: 1.LightGBM, 2.Logistic Regression, 3.SVM, 4.BoostingDT\n')
  temp = int(temp)
  
  if temp == 1:
    # LightGBM
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/LightGBM_user3/lightgbm_model_%s.pickle' % str(i+1), 'rb'))
        preds = model.predict_proba(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

  if temp == 2:
    # Logistic Regression
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/Logistic_Regression_user3/LogisticReg_model_%s.pkl' % str(i+1), 'rb'))
        preds = model.predict_proba(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), np.argmax(preds, axis=-1))
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

  if temp == 3:
    # SVM
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/SVM_user3/SVM_model_%s.pkl' % str(i+1), 'rb'))
        preds = model.predict(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), preds)
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), preds)
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')

  if temp == 4:
    # Boosting Decision Tree
    f1_SCORE = np.empty(10)
    Accuracy = np.empty(10)
    for i in range(10):
        model = pickle.load(open('/content/drive/MyDrive/SEMESTER 7/RECOMMENDATION SYSTEM/Spotify_RecSys/model_based/saved_models/BoostingDT_user3/BoostingDecisionTree_model_%s.pkl' % str(i+1), 'rb'))
        preds = model.predict(user1_X_test)

        f1 = f1_score(user1_y_test.tolist(), preds)
        f1_SCORE[i] = f1

        acc = accuracy_score(user1_y_test.tolist(), preds)
        Accuracy[i] = acc

        print(f"Fold {i+1} model has f1 score: {f1:.5f}\n")
        print(f"Fold {i+1} model has accuracy: {acc:.5f}\n")

    print(f'Average f1 score of {10} folds: {np.mean(f1_SCORE, axis=0)}')
    print(f'Average accuracy of {10} folds: {np.mean(Accuracy, axis=0)}')



In [ ]:
predict_user3(user3_test_csv)

select a model: 1.LightGBM, 2.Logistic Regression, 3.SVM, 4.BoostingDT
3
Fold 1 model has f1 score: 0.00000

Fold 1 model has accuracy: 0.50000

Fold 2 model has f1 score: 0.00000

Fold 2 model has accuracy: 0.40000

Fold 3 model has f1 score: 0.00000

Fold 3 model has accuracy: 0.50000

Fold 4 model has f1 score: 0.00000

Fold 4 model has accuracy: 0.50000

Fold 5 model has f1 score: 0.00000

Fold 5 model has accuracy: 0.50000

Fold 6 model has f1 score: 0.00000

Fold 6 model has accuracy: 0.50000

Fold 7 model has f1 score: 0.00000

Fold 7 model has accuracy: 0.40000

Fold 8 model has f1 score: 0.00000

Fold 8 model has accuracy: 0.50000

Fold 9 model has f1 score: 0.00000

Fold 9 model has accuracy: 0.50000

Fold 10 model has f1 score: 0.00000

Fold 10 model has accuracy: 0.50000

Average f1 score of 10 folds: 0.0
Average accuracy of 10 folds: 0.48
